# Generated by Django 5.0 on 2023-12-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['title'], 'verbose_name': 'Duck', 'verbose_name_plural': 'Ducks'},
        ),
        migrations.AlterField(
            model_name='items',
            name='photo',
            field=models.ImageField(upload_to='../media/photos/'),
        ),
    ]
